version: '3'

services:
  nestjs:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/home/node/app

  db:
    image: bitnami/mongodb:5.0.17
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: routes
